/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/home/components/HomeToolbar': RouteRecordInfo<'/home/components/HomeToolbar', '/home/components/HomeToolbar', Record<never, never>, Record<never, never>>,
    '/home/components/UserMenu': RouteRecordInfo<'/home/components/UserMenu', '/home/components/UserMenu', Record<never, never>, Record<never, never>>,
    '/home/layout/HomeLayout': RouteRecordInfo<'/home/layout/HomeLayout', '/home/layout/HomeLayout', Record<never, never>, Record<never, never>>,
    '/home/pages/HomePage': RouteRecordInfo<'/home/pages/HomePage', '/home/pages/HomePage', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/modules/home/components/HomeToolbar.vue': {
      routes: '/home/components/HomeToolbar'
      views: never
    }
    'src/modules/home/components/UserMenu.vue': {
      routes: '/home/components/UserMenu'
      views: never
    }
    'src/modules/home/layout/HomeLayout.vue': {
      routes: '/home/layout/HomeLayout'
      views: never
    }
    'src/modules/home/pages/HomePage.vue': {
      routes: '/home/pages/HomePage'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
